sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker-compose build

script:
  - docker-compose run --rm praxis-cli bash ./build.sh

after_success:
  - docker-compose run --rm -e BRANCH=$TRAVIS_BRANCH praxis-cli bash ./publish.sh