version: '2'

services:

  praxis-cli:
    build: ./Praxis
    privileged: true
    container_name: praxis-cli

    environment:
      - BRANCH
      - NUGET_API_KEY
      - NUGET_PACKAGES=./vendor

    volumes:
      - "./Praxis:/Praxis"
